default_platform (:android)

platform :android do
  desc "Build APK and Distribute to Firebase"

  lane :beta do
    # Run the build_apk.sh script
    sh "cd /Users/Trung/Desktop/flutter_projects/todo_app/"

    sh "/Users/Trung/Desktop/flutter_projects/todo_app/runner.sh"

    # Distribute to Firebase
    firebase_app_distribution(
      app: "1:165346579800:android:fbeed45319289dc523812d",
      firebase_cli_token: "1//0eRVl3pl6wB8MCgYIARAAGA4SNwF-L9Irx2ZfpoG6qvQjNBoZTWPvjs1hB21C9WTzk-LCAURM4AN2BtDtSNwKW_aWROpZf4vCxeI",
      apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
      groups: "testers"
    )
  end
end

